class StudentDetail {
  String studentID;
  String studentIDOld;
  String lastName;
  String firstName;
  String dateOfBirth;
  String gradeLevel;
  String gender;
  String email;
  String kumonPoints;
  String schoolName;
  String address1;
  String address2;
  String address3;
  String city;
  String stateCode;
  String zipCode;
  String phoneNumber;
  String surveyHowType;
  String originHowSource;
  String surveyWhyType;
  String originWhySource;
  String motherLastName;
  String motherFirstName;
  String motherEmail;
  String motherAddress1;
  String motherAddress2;
  String motherAddress3;
  String motherCity;
  String motherStateCode;
  String motherZipCode;
  String motherHPPhone;
  String motherBPPhone;
  String motherCPPhone;
  String motherFNPhone;
  String motherPNPhone;
  String fatherLastName;
  String fatherFirstName;
  String fatherEmail;
  String fatherAddress1;
  String fatherAddress2;
  String fatherAddress3;
  String fatherCity;
  String fatherStateCode;
  String fatherZipCode;
  String fatherHPPhone;
  String fatherBPPhone;
  String fatherCPPhone;
  String fatherFNPhone;
  String fatherPNPhone;
  String guardianLastName;
  String guardianFirstName;
  String guardianEmail;
  String guardianAddress1;
  String guardianAddress2;
  String guardianAddress3;
  String guardianCity;
  String guardianStateCode;
  String guardianZipCode;
  String guardianHPPhone;
  String guardianBPPhone;
  String guardianCPPhone;
  String guardianFNPhone;
  String guardianPNPhone;
  String otherLastName;
  String otherFirstName;
  String otherEmail;
  String otherAddress1;
  String otherAddress2;
  String otherAddress3;
  String otherCity;
  String otherStateCode;
  String otherZipCode;
  String otherHPPhone;
  String otherBPPhone;
  String otherCPPhone;
  String otherFNPhone;
  String otherPNPhone;
  String subject;
  String kumonGradeLevelStart;
  String workSheetLevelStart;
  String kumonGradeLevel;
  String enrollDate;
  String st1;
  String st2;
  String centerDays;
  String enrollEndDate;
  String partialExemptEndDate;
  String customFilter;

  StudentDetail({
    required this.studentID,
    required this.studentIDOld,
    required this.lastName,
    required this.firstName,
    required this.dateOfBirth,
    required this.gradeLevel,
    required this.gender,
    required this.email,
    required this.kumonPoints,
    required this.schoolName,
    required this.address1,
    required this.address2,
    required this.address3,
    required this.city,
    required this.stateCode,
    required this.zipCode,
    required this.phoneNumber,
    required this.surveyHowType,
    required this.originHowSource,
    required this.surveyWhyType,
    required this.originWhySource,
    required this.motherLastName,
    required this.motherFirstName,
    required this.motherEmail,
    required this.motherAddress1,
    required this.motherAddress2,
    required this.motherAddress3,
    required this.motherCity,
    required this.motherStateCode,
    required this.motherZipCode,
    required this.motherHPPhone,
    required this.motherBPPhone,
    required this.motherCPPhone,
    required this.motherFNPhone,
    required this.motherPNPhone,
    required this.fatherLastName,
    required this.fatherFirstName,
    required this.fatherEmail,
    required this.fatherAddress1,
    required this.fatherAddress2,
    required this.fatherAddress3,
    required this.fatherCity,
    required this.fatherStateCode,
    required this.fatherZipCode,
    required this.fatherHPPhone,
    required this.fatherBPPhone,
    required this.fatherCPPhone,
    required this.fatherFNPhone,
    required this.fatherPNPhone,
    required this.guardianLastName,
    required this.guardianFirstName,
    required this.guardianEmail,
    required this.guardianAddress1,
    required this.guardianAddress2,
    required this.guardianAddress3,
    required this.guardianCity,
    required this.guardianStateCode,
    required this.guardianZipCode,
    required this.guardianHPPhone,
    required this.guardianBPPhone,
    required this.guardianCPPhone,
    required this.guardianFNPhone,
    required this.guardianPNPhone,
    required this.otherLastName,
    required this.otherFirstName,
    required this.otherEmail,
    required this.otherAddress1,
    required this.otherAddress2,
    required this.otherAddress3,
    required this.otherCity,
    required this.otherStateCode,
    required this.otherZipCode,
    required this.otherHPPhone,
    required this.otherBPPhone,
    required this.otherCPPhone,
    required this.otherFNPhone,
    required this.otherPNPhone,
    required this.subject,
    required this.kumonGradeLevelStart,
    required this.workSheetLevelStart,
    required this.kumonGradeLevel,
    required this.enrollDate,
    required this.st1,
    required this.st2,
    required this.centerDays,
    required this.enrollEndDate,
    required this.partialExemptEndDate,
    required this.customFilter,
  });

  @override
  String toString() {
    return 'Student: {StudentID: $studentID, LastName: $lastName, FirstName: $firstName, ...}';
  }
}
